import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className} overflow-x-hidden`}>
        <div className="flex justify-center mt-20">
          <div className="flex justify-center align-center xl:w-2/3 lg:w-3/4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
